---
title: "Artifacts Flow Visualized"
author: "Nazariy Perepichka"
date: "July 10, 2019"
output: html_document
runtime: shiny
---
## Libraries loading
```{r}
library(shiny)
library(leaflet)
library(RColorBrewer)
library(ggplot2)
library(dplyr)
```


## Data loading
```{r}
DATA_PATH = 'data/for_visual.csv'
data <- read.csv(DATA_PATH)
```

## UI calculations
```{r}
min_year <- min(data$year) 
max_year <- if (max(data$year) < 2019) max(data$year) else 2019
```

## User interface
```{r}
ui <- navbarPage("artifacts", id='nav',
  tabPanel("Interactive map",
    div(class="outer",
      tags$head(
        # Include our custom CSS
        includeCSS("styles/index.css")
      ),
      leafletOutput("map", width="100%", height="100%"),
      absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
        draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto",
        width = 450, height = "auto",
        fluidRow(
                 column(12, sliderInput("year_range", label=h3("Years"), min=min_year, max=max_year,  c(min_year, max_year)))
                 )
      )
    )
  )
)
```

```{r}
server <- function(input, output, session) {
  
  artifactsInYears <- reactive({
    year_range = input$year_range
    filter(data, year >= year_range[1] & year <= year_range[2])
  })
  
  output$map <- renderLeaflet({
    directions = artifactsInYears()
    directions <- directions %>%
      arrange(year) %>%
      group_by(artifact_name) %>%
      filter(n() > 1)
      
    directions$lat_start <- ave(directions$lat, directions$artifact_name, FUN=function(x) c(0, x))
    directions$lon_start <- ave(directions$lon, directions$artifact_name, FUN=function(x) c(0, x))
    
    directions <- directions %>%
      filter(lon_start > 0) %>%
      filter(lat_start > 0)
    
    pal <- colorNumeric(palette = "Accent", domain = directions$year, n = 5)
    
    leaflet() %>%
      addProviderTiles(providers$Stamen.TonerLite,
        options = providerTileOptions(noWrap = TRUE)
      ) %>%
      addPolylines(
          data = directions,
          weight = 1,
          opacity = 0.5,
          lng = ~ c(lon_start, lon),
          lat = ~ c(lat_start, lat),
          color = ~pal(year)
      #)
      # This approach to add colors is actually bad
      ) %>%
      addLegend(data = directions, pal = pal, values = ~year, opacity = 0.5)
  })
  
  }
```

```{r}
shinyApp(ui, server)
```
